version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_db
  fastapi:
    build: .
    command: uvicorn main:app --reload
    depends_on:
      - db
    ports:
      - "8000:8000"
